export const LIVESTREAM_TITLE_KEYWORDS = [
  "LIVE",
  "LIVESTREAM",
  "SIARAN LANGSUNG",
  "IBADAH",
  "KEBAKTIAN",
  "PERAYAAN",
  "PELETAKAN",
  "PENEGUHAN",
  "EKSPRESIF",
  "HARI PERJAMUAN KUDUS",
  "PEMBERKATAN",
];
